-- Subscriptions tracking (e.g., ChatGPT Plus)
create table if not exists public.subscriptions (
  id bigint generated by default as identity primary key,
  name text not null,
  amount numeric(12,2) not null default 0,
  currency text not null default 'AED',
  billing_cycle text not null default 'monthly',
  renewal_date date,
  status text not null default 'active',
  notes text,
  "user" text,
  created_at timestamptz not null default now()
);

create index if not exists subscriptions_status_idx on public.subscriptions(status);
create index if not exists subscriptions_user_idx on public.subscriptions("user");
