-- Work data module: monthly attendance/leave tracking
create table if not exists public.workdata (
  id bigint generated by default as identity primary key,
  month date not null,
  days_worked int not null default 0,
  leave_taken int not null default 0,
  annual_leave_total int not null default 0,
  annual_leave_remaining int not null default 0,
  sick_leave_taken int not null default 0,
  unpaid_leave_taken int not null default 0,
  wfh_days int not null default 0,
  overtime_hours numeric(10,2) not null default 0,
  notes text,
  "user" text not null,
  created_at timestamptz not null default now()
);

create index if not exists workdata_user_idx on public.workdata("user");
create index if not exists workdata_month_idx on public.workdata(month);
create unique index if not exists workdata_user_month_key on public.workdata("user", month);

